# .github/workflows/manual-trigger.yml
name: Manual Trigger

on:
  workflow_dispatch:

jobs:
  run-manually:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Print a message
        run: echo "This workflow was triggered manually!"