name: Terraform Apply

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs: 
      run_apply:
        description: Runs tf plan, apply or destroy ?
        type: boolean
        required: false
        default: false
 
env: #exporting by declaring env as an environment 
  AWS_ACCESS_KEY_ID: ${{ secrets.MY_TERRAFORM_LOGIN_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.MY_TERRAFORM_LOGIN_AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1

jobs:
  # 1st job
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: My 1st TF Setup
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.MY_TERRAFORM_LOGIN_TOKEN }}

      - name: Run TF init
        run: terraform init
     
      - name: Check TF Format
        run: terraform formate -check -recursive

      - name: Run TF plan
        run: terraform plan

  # 2nd job
  apply:
    needs: [ plan ]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job steps:
    steps:
      - uses: actions/checkout@v4

      - name: My 1st TF Setup
        uses: hashicorp/setup-terraform@v2
        with:
        #cat ~/.terraform.d/credentials.tfrc.json
        #tree ~/.terraform.d
          cli_config_credentials_token: ${{ secrets.MY_TERRAFORM_LOGIN_TOKEN }}

      - name: Run TF init
        run: terraform init
     
      - name: Check TF Format
        run: terraform formate -check -recursive

      - name: Run TF Apply
        run: terraform apply -auto-approve
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run_apply == 'true' }}



