name: Terraform Destroy

on:
  #push:
    #branches: ["main"]
  workflow_dispatch:
    

env:
  AWS_ACCESS_KEY_ID: ${{}}
  AWS_SECRET_ACCESS_KEY: ${{}}
  AWS_REGION: us-east-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout

      - name: My 1st TF Setup
        uses: hashicorp/setup-terraform
        with:
          cli_config_credentials_token: ${{}}

      - name: Run TF init
        run: terraform init
     
      - name: Check TF Format
        run: terraform fmt -check -recursive

      - name: Run TF plan destroy
        run: terraform plan -destroy
      
      - name: Run TF Apply
        run: terraform destroy -auto-approve